Installing pymapdl to do the testing

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -15,22 +15,108 @@ on:
 
 env:
   MAIN_PYTHON_VERSION: '3.9'
-  PACKAGE_NAME: 'ansys-math'
+  PACKAGE_NAME: 'Ansys Math'
+  PYANSYS_OFF_SCREEN: True
+  DOCKER_PACKAGE: ghcr.io/pyansys/pymapdl/mapdl
+  DOCKER_IMAGE_VERSION_DOCS_BUILD: v22.2.0
+  RESET_PIP_CACHE: 11
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+permissions:
+  packages: read
+
 jobs:
 
-  code-style:
-    name: "Code style checks"
+  # code-style:
+  #   name: "Code style checks"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: "PyAnsys code style checks"
+  #       uses: pyansys/actions/code-style@v2
+  #       with:
+  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}
+  
+  stylecheck:
+    name: Style Check
     runs-on: ubuntu-latest
     steps:
-      - name: "PyAnsys code style checks"
-        uses: pyansys/actions/code-style@v2
+      - uses: actions/checkout@v3
+      - name: Setup Python
+        uses: pyansys/actions/setup-python@v4.3.0
         with:
           python-version: ${{ env.MAIN_PYTHON_VERSION }}
+      - name: Install pre-commit
+        run: pip install pre-commit
+      - name: Run pre-commit
+        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
+
+
+  testimport:
+    name: Smoke Tests
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os: [windows-latest, ubuntu-latest]
+        python-version: ['3.7', '3.8', '3.9', '3.10']
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v4.3.0
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Linux pip cache
+        uses: actions/cache@v3
+        if: ${{ runner.os == 'Linux' }}
+        with:
+          path: ~/.cache/pip
+          key: Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
+          restore-keys: |
+            Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}
+
+      - name: Window pip cache
+        uses: actions/cache@v3
+        if: ${{ runner.os == 'Windows' }}
+        with:
+          path: ~\AppData\Local\pip\Cache
+          key: Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
+          restore-keys: |
+            Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}
+
+      - name: Install PyMAPDL
+        run: pip install .
+
+      - name: Test import
+        working-directory: tests
+        run: python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report(gpu=False))"
+
+      - name: Retrieve PyMAPDL version
+        run: |
+          echo "{PYMAPDL_VERSION}={$(python -c 'from ansys.mapdl.core import __version__; print(__version__)')}" >> $GITHUB_OUTPUT
+          echo "PyMAPDL version is: $(python -c "from ansys.mapdl.core import __version__; print(__version__)")"
+        id: version
+
+      - name: Generate wheelhouse
+        run: pip wheel . -w wheelhouse
+
+      - name: Zip wheelhouse
+        uses: vimtor/action-zip@master
+        with:
+          files: wheelhouse
+          dest: ${{ env.PACKAGE_NAME }}-v${{ steps.version.outputs.PYMAPDL_VERSION }}-wheelhouse-${{ runner.os }}-${{ matrix.python-version }}.zip
+
+      - name: Upload Wheelhouse
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ env.PACKAGE_NAME }}-v${{ steps.version.outputs.PYMAPDL_VERSION }}-wheelhouse-${{ runner.os }}-${{ matrix.python-version }}
+          path: '*.zip'
+          retention-days: 7
+
 
   docs-style:
     name: Documentation Style Check
@@ -51,40 +137,238 @@ jobs:
         with:
           python-version: ${{ env.MAIN_PYTHON_VERSION }}
 
-  tests:
-    name: Build and testing
+
+  build_test:
+    name: Build and Unit Testing
     runs-on: ubuntu-latest
-    needs: [code-style, docs-build]
-  
+    strategy:
+      matrix:
+        mapdl-version: ['v21.1.1', 'v21.2.1', 'v22.1.0', 'v22.2.0', 'v22.2-ubuntu']
+    env:
+      PYMAPDL_PORT: 21000  # default won't work on GitHub runners
+      PYMAPDL_DB_PORT: 21001  # default won't work on GitHub runners
+      PYMAPDL_START_INSTANCE: FALSE
+
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
+      - name: Setup Python
+        uses: actions/setup-python@v4.3.0
         with:
-          python-version: ${{ env.MAIN_PYTHON_VERSION }}
+          python-version: 3.9
 
-      - name: Install dependencies
+      - name: Install OS packages
         run: |
-          python -m pip install --upgrade pip build twine
+          sudo apt update
+          sudo apt install libgl1-mesa-glx xvfb
 
-      - name: Build wheel and sdist
+      - name: Cache pip
+        uses: actions/cache@v3
+        with:
+          path: ~/.cache/pip
+          key: Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
+          restore-keys: |
+            Python-v${{ env.RESET_PIP_CACHE }}-${{ runner.os }}-${{ matrix.python-version }}
+
+      - name: Test virtual framebuffer
         run: |
-          python -m pip install build
+          pip install -r .ci/requirements_test_xvfb.txt
+          xvfb-run python .ci/display_test.py
+
+      - name: Install ansys-mapdl-core
+        run: |
+          pip install build
           python -m build
-          python -m twine check dist/*
+          pip install dist/*.whl
+          xvfb-run python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"
 
-      - name: Install library
-        run: pip install .
+      - name: Login in Github Container registry
+        uses: docker/login-action@v2.1.0
+        with:
+          registry: ghcr.io
+          username: ${{ secrets.GH_USERNAME }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Pull, launch, and validate MAPDL service
+        run: .ci/start_mapdl.sh
+        if: ${{ !contains( matrix.mapdl-version, 'ubuntu') }}
+        env:
+          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
+          MAPDL_IMAGE: ${{ env.DOCKER_PACKAGE }}:${{ matrix.mapdl-version }}
+
+      - name: Pull, launch, and validate Ubuntu MAPDL service from private
+        run: bash .ci/start_mapdl_ubuntu.sh
+        if: ${{ contains( matrix.mapdl-version, 'ubuntu') }}
+        env:
+          LICENSE_SERVER: ${{ secrets.LICENSE_SERVER }}
+          MAPDL_IMAGE: ghcr.io/pyansys/mapdl:${{ matrix.mapdl-version }}
+
+      - name: Unit Testing Requirements Installation
+        run: |
+          pip install .[tests]
 
       - name: Unit Testing
         run: |
-          pip install .[doc,tests]
-          pip install .
-          pytest -m pytest -v --durations=10 --maxfail=10  --reruns 7 --reruns-delay 3 --only-rerun MapdlExitedError  --cov=ansys.mapdl.core --cov-report=xml --cov-report=html
+          xvfb-run pytest -v --durations=10 --maxfail=10  --reruns 7 --reruns-delay 3 --only-rerun MapdlExitedError  --cov=ansys.mapdl.core --cov-report=xml --cov-report=html
 
       - uses: codecov/codecov-action@v3
         name: 'Upload coverage to Codecov'
+
+      - name: Check package
+        run: |
+          pip install twine
+          twine check dist/*
+
+      - name: Upload wheel and binaries
+        uses: actions/upload-artifact@v3
+        with:
+          name: PyMAPDL-packages
+          path: dist/
+          retention-days: 7
+
+      - name: Display files structure
+        if: always()
+        run: |
+          mkdir logs-${{ matrix.mapdl-version }} && echo "Successfully generated directory ${{ matrix.mapdl-version }}"
+          echo "::group:: Display files structure" && ls -R && echo "::endgroup::"
+          ls -R > ./logs-${{ matrix.mapdl-version }}/files_structure.txt
+
+      - name: Display docker files structures
+        if: always()
+        run: |
+          echo "::group:: Display files structure" && docker exec mapdl /bin/bash -c "ls -R" && echo "::endgroup::"
+          docker exec mapdl /bin/bash -c "ls -R" > ./logs-${{ matrix.mapdl-version }}/docker_files_structure.txt
+
+      - name: Collect MAPDL logs on failure
+        if: ${{ always() && !contains( matrix.mapdl-version, 'ubuntu') }}
+        run: |
+          docker exec mapdl /bin/bash -c "mkdir -p /mapdl_logs && echo 'Successfully created directory inside docker container'"
+          docker exec mapdl /bin/bash -c "if compgen -G 'file*.out' > /dev/null ;then cp -f /file*.out /mapdl_logs && echo 'Successfully copied out files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G 'file*.err' > /dev/null ;then cp -f /file*.err /mapdl_logs && echo 'Successfully copied err files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G 'file*.log' > /dev/null ;then cp -f /file*.log /mapdl_logs && echo 'Successfully copied log files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G '*.crash' > /dev/null ;then cp -f /*.crash /mapdl_logs && echo 'Successfully copied crash files.'; fi"
+          docker cp mapdl:/mapdl_logs/. ./logs-${{ matrix.mapdl-version }}/.
+
+
+      - name: Collect MAPDL logs on failure for ubuntu image
+        if: ${{ always() && contains( matrix.mapdl-version,'ubuntu') }}
+        run: |
+          docker exec mapdl /bin/bash -c "mkdir -p /mapdl_logs && echo 'Successfully created directory inside docker container'"
+          docker exec mapdl /bin/bash -c "if compgen -G '/jobs/file*.out' > /dev/null ;then cp -f /jobs/file*.out /mapdl_logs && echo 'Successfully copied out files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G '/jobs/file*.err' > /dev/null ;then cp -f /jobs/file*.err /mapdl_logs && echo 'Successfully copied err files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G '/jobs/file*.log' > /dev/null ;then cp -f /jobs/file*.log /mapdl_logs && echo 'Successfully copied log files.'; fi"
+          docker exec mapdl /bin/bash -c "if compgen -G '/jobs/*.crash' > /dev/null ;then cp -f /jobs/*.crash /mapdl_logs && echo 'Successfully copied crash files.'; fi"
+          docker cp mapdl:/mapdl_logs/. ./logs-${{ matrix.mapdl-version }}/.
+
+      - name: Tar logs
+        if: always()
+        run: |
+          cp log.txt ./logs-${{ matrix.mapdl-version }}/log.txt
+          tar cvzf ./logs-${{ matrix.mapdl-version }}.tgz ./logs-${{ matrix.mapdl-version }}
+
+      - name: Upload logs to GitHub
+        if: always()
+        uses: actions/upload-artifact@master
+        with:
+          name: logs-${{ matrix.mapdl-version }}.tgz
+          path: ./logs-${{ matrix.mapdl-version }}.tgz
+
+      - name: Display MAPDL Logs
+        if: always()
+        run: cat log.txt
+
+      - name: List main files
+        if: always()
+        run: |
+          if compgen -G './logs-${{ matrix.mapdl-version }}/*.err' > /dev/null ;then for f in ./logs-${{ matrix.mapdl-version }}/*.err; do echo "::group:: Error file $f" && cat $f && echo "::endgroup::" ; done; fi
+          if compgen -G './logs-${{ matrix.mapdl-version }}/*.log' > /dev/null ;then for f in ./logs-${{ matrix.mapdl-version }}/*.log; do echo "::group:: Log file $f" && cat $f && echo "::endgroup::" ; done; fi
+          if compgen -G './logs-${{ matrix.mapdl-version }}/*.out' > /dev/null ;then for f in ./logs-${{ matrix.mapdl-version }}/*.out; do echo "::group:: Output file $f" && cat $f && echo "::endgroup::" ; done; fi
+
+  test_windows:
+    name: Unit Testing on Windows
+    runs-on: [self-hosted, Windows, pymapdl]
+
+    steps:
+      - uses: actions/checkout@v3
+
+      # - name: Setup Python
+      #   uses: actions/setup-python@v4.3.2
+      #   with:
+      #     python-version: 3.9
+
+      - name: Checking python_
+        shell: powershell
+        run: |
+          python -m pip install --upgrade pip
+      
+      - name: Creating python venv
+        run: |
+          python -m venv .\.venv
+          .\.venv\Scripts\activate
+
+      - name: Install ansys-mapdl-core
+        shell: powershell
+        run: |
+          python -m pip install build
+          python -m build
+          $FILE_=Resolve-Path '.\dist\*.whl'
+          python -m pip install $FILE_.Path --upgrade
+          python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"
+
+      - name: Unit Testing Requirements Installation
+        shell: powershell
+        run: |
+          python -m pip install .[tests]
+
+      # - name: DPF Server Activation
+      #   run: |
+      #     docker pull ghcr.io/pyansys/dpf-core:22.2dev
+      #     docker run -d --name dpfserver -p ${{ env.DPF_PORT }}:50052 ghcr.io/pyansys/dpf-core:22.2dev && echo "DPF Server active on port ${{ env.DPF_PORT }}."
+
+      - name: Unit Testing
+        run: |
+          set PYMAPDL_PORT=
+          set PYMAPDL_START_INSTANCE=
+          python -m pytest -v --durations=10 --maxfail=10  --reruns 7 --reruns-delay 3 --only-rerun MapdlExitedError  --cov=ansys.mapdl.core --cov-report=xml --cov-report=html
+
+      - uses: codecov/codecov-action@v3
+        name: 'Upload coverage to Codecov'
+
+
+  # tests:
+  #   name: Build and testing
+  #   runs-on: ubuntu-latest
+  #   needs: [code-style, docs-build]
+  
+  #   steps:
+  #     - uses: actions/checkout@v3
+
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}
+
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip build twine
+
+  #     - name: Build wheel and sdist
+  #       run: |
+  #         python -m pip install build
+  #         python -m build
+  #         python -m twine check dist/*
+
+  #     - name: Install library
+  #       run: pip install .
+
+  #     - name: Unit Testing
+  #       run: |
+  #         pip install .[doc,tests]
+  #         pip install .
+  #         pytest -m pytest -v --durations=10 --maxfail=10  --reruns 7 --reruns-delay 3 --only-rerun MapdlExitedError  --cov=ansys.mapdl.core --cov-report=xml --cov-report=html
+
+  #     - uses: codecov/codecov-action@v3
+  #       name: 'Upload coverage to Codecov'
 
   release:
 
